### PR TITLE
Feature: Limit progress slider to current chapter for books with chapters

### PR DESCRIPTION
**Pull request by pichfl**
Re #71

### CODE REVIEW

**Comment by GianniCarlo** [comment]
Just one comment, if I drag the slider up to the end and hold it, the player will start skipping in a rapid way the chapters. I think we should imitate Audible's interaction, that you may drag it to the end of the chapter, but only when the finger is raised, the following chapter is started. Thoughts?

**Comment by pichfl** [comment]
That will be an interesting thing to solve, but I agree.

**Comment by pichfl** [comment]
I'm still missing one edge case, please wait with the merge

**Comment by GianniCarlo** [comment]
awesome!

**Pull request merged**
