### PR TITLE
Feature: Improve empty states for library and playlists

### PR DESCRIPTION
**Pull request by pichfl**
Re #73

### CODE REVIEW

**Comment by GianniCarlo** [comment]
Possibly too much text, we could use this space just as a hint for the dragging functionality. I think we could do without the explicit part about importing files and maybe let the user find out the part where importing an existing file just moves the book around 🤔
img_bb12c7ce1d6b-1

**Comment by pichfl** [comment]
Agreed. I'll update the PR with a shorter text.

**Comment by GianniCarlo** [comment]
Do we need the spacer views? wouldn't it be cleaner to have the images center themselves vertically in relation to their superview. Maybe put an offset of `-41` to simulate the current position that their in. With that in place, the spacer views in both the player and playlist VCs could be deleted with no conflict

**Comment by pichfl** [comment]
The spacers are used because I want to keep the views in balance when the length of the help text changes which depends on the system font size and/or localization. It's not necessary for the library but I thought keeping both views similar didn't hurt. We could consider extracting the empty state into a xib later on.

**Pull request merged**
